version: '3.9'

services:
  ec_registry:
    build:
      context: .
      dockerfile: EC_Registry/Dockerfile
    container_name: ec_registry

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://192.168.100.100:5432/easycab
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

    volumes:
      - server:/server
      - shared:/shared
    ports:
      - "8443:8443"
    networks:
      easycab_network:
        ipv4_address: 192.168.100.5

  ec_de_1:
    build:
      context: .
      dockerfile: EC_DE/Dockerfile
    container_name: ec_de_1
    volumes:
      - client:/client
      - shared:/shared
    environment:
      SPRING_APPLICATION_NAME: EC_DE
      SPRING_KAFKA_BOOTSTRAP-SERVERS: 192.168.100.3:9092
      CENTRAL_IP: 192.168.100.4
      CENTRAL_PORT: 8081
      TAXI_ID: 1
      SENSOR_PORT: 5001
      REGISTRY_URL: https://192.168.100.5:8443/taxis
    depends_on:
      - ec_registry
    ports:
      - "8001:8080"
    stdin_open: true
    tty: true
    networks:
      easycab_network:
        ipv4_address: 192.168.100.101

  ec_de_2:
    build:
      context: .
      dockerfile: EC_DE/Dockerfile
    container_name: ec_de_2
    volumes:
      - client:/client
      - shared:/shared
    environment:
      SPRING_APPLICATION_NAME: EC_DE
      SPRING_KAFKA_BOOTSTRAP-SERVERS: 192.168.100.3:9092
      CENTRAL_IP: 192.168.100.4
      CENTRAL_PORT: 8081
      TAXI_ID: 2
      SENSOR_PORT: 5002
      REGISTRY_URL: https://192.168.100.5:8443/taxis
    ports:
      - "8002:8080"
    stdin_open: true
    tty: true
    depends_on:
      - ec_registry
    networks:
      easycab_network:
        ipv4_address: 192.168.100.102

networks:
  easycab_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24

volumes:
  server:
  shared:
  client:
