version: '3.9'
services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: easycab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      easycab_network:
        ipv4_address: 192.168.100.30
    volumes:
      - postgres_data:/var/lib/postgresql/data
  ec_central:
    build:
      context: .
      dockerfile: ./EC_Central/Dockerfile
    image: ec-central:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://192.168.1.16:5432/easycab
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 198.19.249.20:9092
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
      - "9090:9090"
    networks:
      - easycab_network
    depends_on:
      - postgres
volumes:
  postgres_data:

networks:
  easycab_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
